# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See https://symfony.com/doc/current/routing.html

controllers:
    resource: ../src/Controller/
    type: attribute
