controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Rediriger la page d'accueil vers le login
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_login
        permanent: true
